### ISSUE TITLE
The README for evb_rk3399 is incorrect. bl31.bin is too large.

### ISSUE THREAD

**Issue by AlexanderAmelkin** [rockchip-linux/u-boot#1]
The README here:
https://github.com/rockchip-linux/u-boot/blob/release/board/rockchip/evb_rk3399/README
says I need to generate a bl31.bin file from ARM Trusted Firmware.
However, when done as per that README, the generated bl31.bin file gets as huge as 4GB and cannot be used. 

ARM believes they should disable generating bl31.bin for rk3399, which will render the README even more incorrect. Please read the related ticket at TF:
https://github.com/ARM-software/tf-issues/issues/449

Please fix the README so that it could be used to actually create the boot loader for rk3399.

**Comment by wzyy2** [comment]
Sorry to answer now.

Could you send it on uboot mali list(cc kever.yang@rock-chips.com)
