### ISSUE TITLE
linux下获取uboot中的环境变量

### ISSUE THREAD

**Issue by nova-wenbo** [rockchip-linux/u-boot#14]
hello ！ 我使用这个最新的uboot跑在开发板上，使用4.4内核，想在开发板上的linux系统下获取uboot的环境变量，我编译了uboot中的tools/env/fw_printenv，但是不能读到正确的环境变量，我发现修改fw_env.config和fw_env.h中的分区名字和地址偏移，这个怎么修改fw_env.config和fw_env.h才能访问到flash中uboot环境变量呢

**Comment by wzyy2** [comment]
I saw kever have send some patches about env yesterday, i think it might help you.

https://patchwork.ozlabs.org/patch/832273/
https://patchwork.ozlabs.org/patch/832272/
https://patchwork.ozlabs.org/patch/832299/

It seems partition table is also updated.
http://opensource.rock-chips.com/wiki_Partitions

**Comment by nova-wenbo** [comment]
I am most grateful to you.
