### ISSUE TITLE
Didn't generate u-boot-spl-dtb.bin file

### ISSUE THREAD

**Issue by sprhawk** [rockchip-linux/u-boot#2]
I used 
    https://github.com/rockchip-linux/manifests 

with branch morty, follow the instructions.

But during build, the u-boot didn't generate u-boot-spl-dtb.bin file, then the whole project didn't continue to build.

in its build directory, it has following files:

    u-boot-spl
    u-boot-spl.bin
    u-boot-spl.dtb
    u-boot-spl.lds
    u-boot-spl.map
    u-boot-spl-nodtb.bin

I used following configuration under manifests:

    MACHINE=firefly3288 . setup_environment -e wayland
    bitbake core-image-weston

**Comment by wzyy2** [comment]
https://github.com/rockchip-linux/u-boot/commit/ffd1211bd92bcf894afcabbcf74341bc8b706037 should fix it.
