### ISSUE TITLE
how to sign MiniLoaderAll.bin？

### ISSUE THREAD

**Issue by YumingMa** [rockchip-linux/u-boot#25]
Dear，

There is a tool named SecureBootConsole on linux. I use this tool to sign MiniLoaderALL.bin for rk3399.
run the command and sign sucessfully, but the device can't boot failed. 
How to sign it?

the command:
./SecureBootConsole -p  -slxb  privateKey.bin publicKey.bin  MiniLoaderAll.bin

the error log:
Boot1: 2017-06-09, version: 1.09
CPUId = 0x0
ChipType = 0x10, 1901
SdmmcInit=2 0
BootCapSize=100000
UserCapSize=7456MB
FwPartOffset=2000 , 100000
SdmmcInit=0 20
StorageInit ok = 66694
powerOn 479026
DDR Version 1.08 20170320
In
Channel 0: DDR3, 800MHz
Bus Width=32 Col=10 Bank=8 Row=15 CS=1 Die Bus-Width=16 Size=1024MB
Channel 1: DDR3, 800MHz
Bus Width=32 Col=10 Bank=8 Row=15 CS=1 Die Bus-Width=16 Size=1024MB
256B stride
ch 0 ddrconfig = 0x101, ddrsize = 0x20
ch 1 ddrconfig = 0x101, ddrsize = 0x20
pmugrf_os_reg[2] = 0x32817281, stride = 0x9
OUT
Boot1: 2017-06-09, version: 1.09
CPUId = 0x0
ChipType = 0x10, 1831
SdmmcInit=2 0
BootCapSize=100000
UserCapSize=7456MB
FwPartOffset=2000 , 100000
SdmmcInit=0 20
StorageInit ok = 65880
SEC = 1
SecureInit 4 66091
secure head flag:0x0
SecureInit 404 66862
secure head flag:0x0
SecureInit 804 67580
secure head flag:0x0
SecureInit c04 68297
secure head flag:0x0
SecureInit 1004 69026
secure head flag:0x0
SecureInit 1404 69752
secure head flag:0x0
SecureInit 1804 70396
secure head flag:0x0
SecureInit 1c04 71039
secure head flag:0x0
SecureInit 2004 71680
secure head flag:0x0
SecureInit 2404 72321
secure head flag:0x0
SecureInit 2804 72956
secure head flag:0x0
SecureInit 2c04 73599
secure head flag:0x0
SecureInit 3004 74245
secure head flag:0x0
SecureInit 3404 74890
secure head flag:0x0
SecureInit 3804 75532
secure head flag:0x0
SecureInit 3c04 76174
secure head flag:0x0
check key error
powerOn 489047

**Comment by hrushirajg23** [comment]
where is the SecureBootConsole tool ?
Can you provide link please ?
