### ISSUE TITLE
Please enable CONFIG_API

### ISSUE THREAD

**Issue by fuzxxl** [rockchip-linux/u-boot#3]
Hello!

I would like to run the Tinker Board with FreeBSD. FreeBSD can boot with U-Boot, but it needs the `CONFIG_API` option to be enabled to do so. Could you please enable it so I can build an U-Boot that can boot FreeBSD?

Thank you very much.

**Comment by wzyy2** [comment]
Hi,

You could enable it in your local branch.

**Comment by fuzxxl** [comment]
If you could enable that by default, some useful use cases, like dual booting Linux and FreeBSD are possible.

Also, while I managed to get U-Boot to build and run on the TinkerBoard, there is no TTY output from U-Boot for some reason.

**Comment by eddiecailinux** [comment]
we don't want to maintain too many local patches. you can send any patches you want to upstream.  and we are happy to review it.
