### ISSUE TITLE
RK3288 : Wrong memory size reported

### ISSUE THREAD

**Issue by Kwiboo** [rockchip-linux/u-boot#8]
After recent changes to use common sdram functions my Tinker Board reports less then 1GB of memory.

Reverting https://github.com/rockchip-linux/u-boot/compare/30d669965e83f2f7dec2bce48707b9d9e73978c6...cc763d4f6f468ef6daacb0077faa1da2c887c719 fixes the issue.

Before revert:
```
LibreELEC:~ # cat /proc/meminfo
MemTotal:         762360 kB
MemFree:          459260 kB
MemAvailable:     592524 kB
```

After revert:
```
LibreELEC:~ # cat /proc/meminfo
MemTotal:        2061512 kB
MemFree:         1569396 kB
MemAvailable:    1755636 kB
```

**Comment by wzyy2** [comment]
@keveryang

**Comment by wzyy2** [comment]
It have break some boards, so let me revert it, until kever give it a fix.

**Comment by keveryang** [comment]
Please try with below patch:
https://github.com/keveryang/u-boot/commit/6e9eec076b6d5fc892b7da5f84d6a1ef9c13706e
I test with firefly-rk3288 with 2GB ddr3.

I have send the changes to upstream, but I have no enough time to rebase this branch now, sorry.

**Comment by Kwiboo** [comment]
@keveryang that patch fixed my issue and the Tinker Board is now reporting 2GB again, thanks!
